apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: days85/movieapp-rating:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8082
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8082
  selector:
    app: rating